logging:
  level:
    org.suym.ai.kbs: DEBUG
    dev.langchain4j: DEBUG

spring:
  evn: dev
  application:
    name: kbs
server:
  port: 10483

milvus:
  host: localhost
  port: 19530
  # 默认
  default:
    collection-name: enterprise_knowledge_v2
    dimension: 384
  # 商品
  goods:
    collection-name: goods_store_v1
    dimension: 512
  # 画廊
  gallery:
    collection-name: image_gallery_v1
    dimension: 512

llm:
  openai:
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1 # 阿里云百炼兼容模式 endpoint
    api-key: sk-be4abd8c25ad40c5b495b29795ac2144
    model-name: qwen-plus


clip:
  model:
    text-path: "C:/Users/18699/Desktop/AI/计算机视觉/clip模型/text_model.onnx"
    tokenizer-path: "C:/Users/18699/Desktop/AI/计算机视觉/clip模型/tokenizer.json"
    vision-path: "C:/Users/18699/Desktop/AI/计算机视觉/clip模型/vision_model.onnx"